name: Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to release"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  image:
    runs-on: ubuntu-latest
    name: Release Actions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build action image
        id: image_build
        run: |
          RELEASE_TAG="${{ github.ref_name }}${{ github.event.inputs.tag_name }}"
          major=$(echo $RELEASE_TAG | cut -d. -f1)
          minor=$(echo $RELEASE_TAG | cut -d. -f2)

          docker buildx build \
            --build-arg FETCH_CHECKSUMS=yes \
            --build-arg VERSION="${RELEASE_TAG:1}" \
            --tag ghcr.io/$IMAGE_NAME:$RELEASE_TAG \
            --tag ghcr.io/$IMAGE_NAME:$major \
            --tag ghcr.io/$IMAGE_NAME:$major.$minor \
            --platform linux/amd64,linux/arm64 \
            --push \
            --iidfile manifest-list-digest.txt \
            .

          echo "digest=$(<manifest-list-digest.txt)" >> "$GITHUB_OUTPUT"
